name: Waka_Readme

on:
  push:
  schedule:
    - cron: '* 4/6 * * *'

jobs:
  update-readme:
    name: update metrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKA_KEY }}
