name: Waka_Readme

on:
  push:
  schedule:
    - cron: '* 4/6 * * *'

jobs:
  update-readme:
    name: update metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: 'False'
          SHOW_OS: 'False'
          SHOW_DAYS_OF_WEEK: 'False'
          SHOW_COMMIT: 'False'
          SYMBOL_VERSION: 2
