name: Waka_Readme

on:
  workflow_dispatch:
  schedule:
    - cron: '* 4 * * *'

jobs:
  update-readme:
    name: update metrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.ANMOL }}
          SHOW_TITLE: true
          TIME_RANGE: last_7_days
          BLOCKS: .✎
          SHOW_TIME: true
          SHOW_MASKED_TIME: true
          LANG_COUNT: 5
